# Generated by Django 4.0.3 on 2022-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0002_tranporter_v_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='0000000', max_length=50)),
                ('g_type', models.CharField(default='0000000', max_length=50)),
                ('src', models.CharField(default='0000000', max_length=50)),
                ('dest', models.CharField(default='0000000', max_length=50)),
                ('weight', models.CharField(default='0000000', max_length=50)),
                ('dist', models.CharField(default='0000000', max_length=50)),
            ],
        ),
    ]
