# Generated by Django 4.0.3 on 2022-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstar', '0004_alter_company_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='weight',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
